#!/bin/bash
FILE=/update7to8-phase1-done
if test -f "$FILE" 
then
  yum -y install dnf 
  dnf -y remove yum yum-metadata-parser
  rm -Rf /etc/yum
  dnf -y update
  dnf install http://vault.centos.org/8.5.2111/BaseOS/x86_64/os/Packages/{centos-linux-repos-8-3.el8.noarch.rpm,centos-linux-release-8.5-1.2111.el8.noarch.rpm,centos-gpg-keys-8-3.el8.noarch.rpm}
  dnf -y upgrade https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  dnf clean all
  rpm -e `rpm -q kernel`
  rpm -e --nodeps sysvinit-tools
  cat /etc/os-release
else
  yum -y update
  yum -y install epel-release
  yum -y install rpmconf yum-utils
  rpmconf -a
  package-cleanup --leaves
  package-cleanup --orphans
  touch /update7to8-phase1-done
  reboot -f
fi
